baseURL = 'https://tflester.com/'
locale = 'en-us'
title = 'Tim Lester'


[menu]
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 10
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 20

[module]
    [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/gohugo-ananke/ananke/v2'

[params]
    [params.ananke]
    show_recent_posts = false
