baseURL = 'https://tflester.com/'
locale = 'en-us'
title = 'Tim Lester'
enableGitInfo = true

[params]
  githubRepo = 'https://github.com/tfrancisl/tfrancisl.github.io'

[params.blog]
  showToc = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 4

[menu]
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 10
  [[menu.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 20
  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 30
